const days=[ 
    'Today', 
    'Tomorrow', 
]

const times=[
    '9:00 AM', 
    '11:10 AM', 
    '12:00 PM', 
    '1:50 PM', 
    '4:30 PM', 
    '6:00 PM', 
    '7:10 PM', 
    '9:45 PM'
]

export const movies=[
    {
        key: 1,
        title: "La La Land",
        poster: 'https://i.imgur.com/po7UezG.jpg',
        genre: 'Drama/Romance',
        days,
        times,
      },
      {
        key: 2,
        title: 'Paterson',
        poster: 'https://i.imgur.com/pE0C9E0.jpg',
        genre: 'Drama/Comedy',
        days,
        times,
      },
      {
        key: 3,
        title: 'Jackie',
        poster: 'https://i.imgur.com/VqUi1sw.jpg',
        genre: 'Drama/Biography',
        days,
        times,
      },
      {
        key: 4,
        title: 'Lo and Behold Reveries of the Connected World',
        poster: 'https://i.imgur.com/s106X7S.jpg',
        genre: 'Documentary',
        days,
        times,
      },
      {
        key: 5,
        title: '10 Cloverfield Lane',
        poster: 'https://i.imgur.com/kV2BVdH.jpg',
        genre: 'Thriller/Science Fiction',
        days,
        times,
      },
      {
        key: 6,
        title: 'Birth of a Nation',
        poster: 'https://i.imgur.com/a6HJj8S.jpg',
        genre: 'Fantasy/Mystery',
        days,
        times,
      },
      {
        key: 7,
        title: 'De Palma',
        poster: 'https://i.imgur.com/oOIa73M.jpg',
        genre: 'Documentary',
        days,
        times,
      },
      {
        key: 8,
        title: 'Doctor Strange',
        poster: 'https://i.imgur.com/kyHDVOk.jpg',
        genre: 'Fantasy/Science Fiction',
        days,
        times,
      },
      {
        key: 9,
        title: 'Eddie the Eagle',
        poster: 'https://i.imgur.com/GNrdAuF.jpg',
        genre: 'Drama/Sport',
        days,
        times,
      },
      {
        key: 10,
        title: 'Pride and prejudice and zombies',
        poster: 'https://i.imgur.com/KhbG0Lw.jpg',
        genre: 'Thriller/Action',
        days,
        times,
      },
      {
        key: 11,
        title: 'Finding Dory',
        poster: 'https://i.imgur.com/BTexHYJ.jpg',
        genre: 'Comedy/Adventure',
        days,
        times,
      },
      {
        key: 12,
        title: 'Green Room',
        poster: 'https://i.imgur.com/Q0Ysh7L.jpg',
        genre: 'Crime/Thriller',
        days,
        times,
      },
      {
        key: 13,
        title: 'Kubo and the Two Strings',
        poster: 'https://i.imgur.com/uTFCKZc.jpg',
        genre: 'Fantasy/Adventure',
        days,
        times,
      },
      {
        key: 14,
        title: 'In a Valley of Violence',
        poster: 'https://i.imgur.com/DTtJ62G.jpg',
        genre: 'Drama/Western',
        days,
        times,
      },
      {
        key: 15,
        title: 'O.J.: Made in America',
        poster: 'https://i.imgur.com/T8uc6x8.jpg',
        genre: 'Documentary',
        days,
        times,
      },
      {
        key: 16,
        title: 'Rogue One: A Star Wars Story',
        poster: 'https://i.imgur.com/zOF2iYc.jpg',
        genre: 'Science Fiction/Action',
        days,
        times,
      },
      {
        key: 17,
        title: 'Sing Street',
        poster: 'https://i.imgur.com/C3ExEb6.jpg',
        genre: 'Drama/Romance',
        days,
        times,
      },
      {
        key: 18,
        title: 'Zoolander 2',
        poster: 'https://i.imgur.com/ejlIijD.jpg',
        genre: 'Comedy',
        days,
        times,
      },
]